services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    ports:
      - "  :80" # Exponer el puerto 80 del contenedor en el puerto 8080 del host
    volumes:
      - mediawiki_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mediawiki_db
    environment:
      - MYSQL_ROOT_PASSWORD=usuario
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - db_data:         # Volumen para persistir los datos de la base de datos que están en /var/lib/mysql

volumes:
  mediawiki_data:
    driver: local
  db_data:
    driver: local